package main

import (
	"context"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"time"

	"github.com/spf13/cobra"

	"github.com/multica-ai/multica/server/internal/cli"
)

// ---------------------------------------------------------------------------
// Phase 1b CLI additions: summarise, versioning, comments, export.
// Registered under the same docsCmd tree as Phase 1a.
// ---------------------------------------------------------------------------

var docsSummariseCmd = &cobra.Command{
	Use:   "summarise <attachment-id>",
	Short: "Write (or overwrite) the summary field on a document",
	Long: `Set the summary text for a document. This is the field surfaced
under the title in the library viewer and in the sidebar tree. Pass the
summary via --summary or pipe it on stdin.

Summaries can also be produced by an autopilot that walks
` + "`multica docs list-unsummarised`" + ` and writes to this endpoint.`,
	Example: `  # Set a summary directly
  $ multica docs summarise 019dbb... --summary "Exec pack overview"

  # Pipe a summary via stdin (useful when generated by an LLM)
  $ echo "Exec pack overview" | multica docs summarise 019dbb... --summary-stdin`,
	Args: exactArgs(1),
	RunE: runDocsSummarise,
}

var docsListUnsummarisedCmd = &cobra.Command{
	Use:   "list-unsummarised",
	Short: "List documents with no summary (for autopilot targeting)",
	Long: `Walk the workspace (or an issue/project) and return every document
that has no summary yet. The typical autopilot loop is: call this, read
each attachment's content, write a summary via ` + "`multica docs summarise`" + `.`,
	RunE: runDocsListUnsummarised,
}

var docsVersionsCmd = &cobra.Command{
	Use:   "versions <attachment-id>",
	Short: "Show version history for a document",
	Args:  exactArgs(1),
	RunE:  runDocsVersions,
}

var docsNewVersionCmd = &cobra.Command{
	Use:   "new-version <existing-attachment-id> <new-attachment-id>",
	Short: "Register a newly-uploaded attachment as the next version of an existing document",
	Long: `After uploading a new file (via ` + "`multica issue comment add --attachment`" + ` or
the equivalent), promote it as the next version of an existing document.
The new attachment's content becomes the head; older versions remain
accessible under the same document_id.`,
	Args: exactArgs(2),
	RunE: runDocsNewVersion,
}

var docsCommentCmd = &cobra.Command{
	Use:   "comment",
	Short: "Manage comments attached to a document",
}

var docsCommentAddCmd = &cobra.Command{
	Use:   "add <attachment-id>",
	Short: "Add a comment to a document",
	Args:  exactArgs(1),
	RunE:  runDocsCommentAdd,
}

var docsCommentListCmd = &cobra.Command{
	Use:   "list <attachment-id>",
	Short: "List comments on a document",
	Args:  exactArgs(1),
	RunE:  runDocsCommentList,
}

var docsCommentDeleteCmd = &cobra.Command{
	Use:   "delete <comment-id>",
	Short: "Delete a document comment",
	Args:  exactArgs(1),
	RunE:  runDocsCommentDelete,
}

var docsExportCmd = &cobra.Command{
	Use:   "export",
	Short: "Download a zip bundle of library documents",
	Long: `Download an entire issue or project library, or a named section,
as a zip file. Exactly one of --issue, --project, or --section is required.`,
	Example: `  # Whole project library
  $ multica docs export --project proj-xyz --output project.zip

  # One issue
  $ multica docs export --issue abc --output issue.zip

  # One section
  $ multica docs export --section sec-123 --output section.zip`,
	RunE: runDocsExport,
}

func init() {
	docsCmd.AddCommand(docsSummariseCmd)
	docsCmd.AddCommand(docsListUnsummarisedCmd)
	docsCmd.AddCommand(docsVersionsCmd)
	docsCmd.AddCommand(docsNewVersionCmd)
	docsCmd.AddCommand(docsCommentCmd)
	docsCommentCmd.AddCommand(docsCommentAddCmd)
	docsCommentCmd.AddCommand(docsCommentListCmd)
	docsCommentCmd.AddCommand(docsCommentDeleteCmd)
	docsCmd.AddCommand(docsExportCmd)

	docsSummariseCmd.Flags().String("summary", "", "Summary text (required unless --summary-stdin)")
	docsSummariseCmd.Flags().Bool("summary-stdin", false, "Read summary from stdin instead of --summary")

	docsListUnsummarisedCmd.Flags().String("issue", "", "Scope to one issue")
	docsListUnsummarisedCmd.Flags().String("project", "", "Scope to one project")
	docsListUnsummarisedCmd.Flags().String("output", "json", "Output format: json or table")

	docsNewVersionCmd.Flags().String("notes", "", "Version notes (e.g. what changed)")

	docsCommentAddCmd.Flags().String("content", "", "Comment content (required unless --content-stdin)")
	docsCommentAddCmd.Flags().Bool("content-stdin", false, "Read content from stdin")
	docsCommentAddCmd.Flags().String("parent", "", "Parent comment ID (for threaded replies)")

	docsExportCmd.Flags().String("issue", "", "Issue ID to export")
	docsExportCmd.Flags().String("project", "", "Project ID to export")
	docsExportCmd.Flags().String("section", "", "Section ID to export")
	docsExportCmd.Flags().Bool("workspace", false, "Export the whole workspace library")
	docsExportCmd.Flags().StringP("output", "o", "", "Output path (defaults to <scope>-library.zip)")
}

// ---------------------------------------------------------------------------
// summarise: writes to the existing curation endpoint with only the summary
// field set. Reuses the COALESCE upsert semantics so other fields stay put.
// ---------------------------------------------------------------------------

func runDocsSummarise(cmd *cobra.Command, args []string) error {
	client, err := newAPIClient(cmd)
	if err != nil {
		return err
	}
	attachmentID := args[0]

	var summary string
	useStdin, _ := cmd.Flags().GetBool("summary-stdin")
	if useStdin {
		data, err := io.ReadAll(os.Stdin)
		if err != nil {
			return fmt.Errorf("read summary from stdin: %w", err)
		}
		summary = string(data)
	} else {
		summary, _ = cmd.Flags().GetString("summary")
	}
	if summary == "" {
		return fmt.Errorf("summary is required (use --summary or --summary-stdin)")
	}

	ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
	defer cancel()

	var result map[string]any
	payload := map[string]any{"summary": summary}
	if err := client.PutJSON(ctx, "/api/documents/"+attachmentID+"/curation", payload, &result); err != nil {
		return fmt.Errorf("summarise document: %w", err)
	}
	fmt.Fprintln(os.Stderr, "Summary saved for", attachmentID)
	return cli.PrintJSON(os.Stdout, result)
}

func runDocsListUnsummarised(cmd *cobra.Command, _ []string) error {
	client, err := newAPIClient(cmd)
	if err != nil {
		return err
	}
	issueID, _ := cmd.Flags().GetString("issue")
	projectID, _ := cmd.Flags().GetString("project")

	path := "/api/documents/unsummarised"
	if issueID != "" && projectID != "" {
		return fmt.Errorf("provide --issue OR --project, not both")
	}
	if issueID != "" {
		path += "?issue_id=" + issueID
	} else if projectID != "" {
		path += "?project_id=" + projectID
	}

	ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
	defer cancel()

	var result map[string]any
	if err := client.GetJSON(ctx, path, &result); err != nil {
		return fmt.Errorf("list unsummarised: %w", err)
	}

	output, _ := cmd.Flags().GetString("output")
	if output == "table" {
		docs, _ := result["documents"].([]any)
		headers := []string{"ATTACHMENT ID", "FILENAME", "TYPE", "SIZE"}
		rows := make([][]string, 0, len(docs))
		for _, d := range docs {
			doc, _ := d.(map[string]any)
			if doc == nil {
				continue
			}
			rows = append(rows, []string{
				truncateID(strVal(doc, "attachment_id")),
				strVal(doc, "filename"),
				strVal(doc, "content_type"),
				fmt.Sprintf("%v", doc["size_bytes"]),
			})
		}
		cli.PrintTable(os.Stdout, headers, rows)
		return nil
	}
	return cli.PrintJSON(os.Stdout, result)
}

// ---------------------------------------------------------------------------
// Versioning
// ---------------------------------------------------------------------------

func runDocsVersions(cmd *cobra.Command, args []string) error {
	client, err := newAPIClient(cmd)
	if err != nil {
		return err
	}
	attachmentID := args[0]

	ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
	defer cancel()

	var result map[string]any
	if err := client.GetJSON(ctx, "/api/documents/"+attachmentID+"/versions", &result); err != nil {
		return fmt.Errorf("list versions: %w", err)
	}
	return cli.PrintJSON(os.Stdout, result)
}

func runDocsNewVersion(cmd *cobra.Command, args []string) error {
	client, err := newAPIClient(cmd)
	if err != nil {
		return err
	}
	existingID := args[0]
	newID := args[1]
	notes, _ := cmd.Flags().GetString("notes")

	payload := map[string]any{"attachment_id": newID}
	if notes != "" {
		payload["notes"] = notes
	}

	ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
	defer cancel()

	var result map[string]any
	if err := client.PostJSON(ctx, "/api/documents/"+existingID+"/versions", payload, &result); err != nil {
		return fmt.Errorf("create version: %w", err)
	}
	return cli.PrintJSON(os.Stdout, result)
}

// ---------------------------------------------------------------------------
// Comments
// ---------------------------------------------------------------------------

func runDocsCommentAdd(cmd *cobra.Command, args []string) error {
	client, err := newAPIClient(cmd)
	if err != nil {
		return err
	}
	attachmentID := args[0]

	var content string
	useStdin, _ := cmd.Flags().GetBool("content-stdin")
	if useStdin {
		data, err := io.ReadAll(os.Stdin)
		if err != nil {
			return fmt.Errorf("read content from stdin: %w", err)
		}
		content = string(data)
	} else {
		content, _ = cmd.Flags().GetString("content")
	}
	if content == "" {
		return fmt.Errorf("content is required (use --content or --content-stdin)")
	}
	parent, _ := cmd.Flags().GetString("parent")

	payload := map[string]any{"content": content}
	if parent != "" {
		payload["parent_id"] = parent
	}

	ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
	defer cancel()

	var result map[string]any
	if err := client.PostJSON(ctx, "/api/documents/"+attachmentID+"/comments", payload, &result); err != nil {
		return fmt.Errorf("add comment: %w", err)
	}
	return cli.PrintJSON(os.Stdout, result)
}

func runDocsCommentList(cmd *cobra.Command, args []string) error {
	client, err := newAPIClient(cmd)
	if err != nil {
		return err
	}
	attachmentID := args[0]

	ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
	defer cancel()

	var result map[string]any
	if err := client.GetJSON(ctx, "/api/documents/"+attachmentID+"/comments", &result); err != nil {
		return fmt.Errorf("list comments: %w", err)
	}
	return cli.PrintJSON(os.Stdout, result)
}

func runDocsCommentDelete(cmd *cobra.Command, args []string) error {
	client, err := newAPIClient(cmd)
	if err != nil {
		return err
	}
	commentID := args[0]

	ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
	defer cancel()

	if err := client.DeleteJSON(ctx, "/api/documents/comments/"+commentID); err != nil {
		return fmt.Errorf("delete comment: %w", err)
	}
	fmt.Fprintln(os.Stderr, "Deleted comment", commentID)
	return nil
}

// ---------------------------------------------------------------------------
// Export
// ---------------------------------------------------------------------------

func runDocsExport(cmd *cobra.Command, _ []string) error {
	issueID, _ := cmd.Flags().GetString("issue")
	projectID, _ := cmd.Flags().GetString("project")
	sectionID, _ := cmd.Flags().GetString("section")
	workspace, _ := cmd.Flags().GetBool("workspace")
	outputPath, _ := cmd.Flags().GetString("output")

	set := 0
	var urlPath, defaultName string
	if issueID != "" {
		set++
		urlPath = "/api/issues/" + issueID + "/library/export.zip"
		defaultName = "issue-" + issueID + "-library.zip"
	}
	if projectID != "" {
		set++
		urlPath = "/api/projects/" + projectID + "/library/export.zip"
		defaultName = "project-" + projectID + "-library.zip"
	}
	if sectionID != "" {
		set++
		urlPath = "/api/library/sections/" + sectionID + "/export.zip"
		defaultName = "section-" + sectionID + ".zip"
	}
	if workspace {
		set++
		urlPath = "/api/library/export.zip"
		defaultName = "workspace-library.zip"
	}
	if set != 1 {
		return fmt.Errorf("exactly one of --issue, --project, --section, or --workspace is required")
	}
	if outputPath == "" {
		outputPath = defaultName
	}

	client, err := newAPIClient(cmd)
	if err != nil {
		return err
	}

	// Download via the authed client. The existing DownloadFile helper
	// handles relative URL resolution and auth headers correctly (fixed
	// in PR #1585).
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Minute)
	defer cancel()

	data, err := client.DownloadFile(ctx, urlPath)
	if err != nil {
		return fmt.Errorf("download zip: %w", err)
	}

	if err := os.MkdirAll(filepath.Dir(outputPath), 0o755); err != nil {
		return fmt.Errorf("create output dir: %w", err)
	}
	if err := os.WriteFile(outputPath, data, 0o644); err != nil {
		return fmt.Errorf("write zip: %w", err)
	}

	fmt.Fprintf(os.Stderr, "Exported %d bytes to %s\n", len(data), outputPath)
	return cli.PrintJSON(os.Stdout, map[string]any{
		"path":  outputPath,
		"bytes": len(data),
	})
}

